//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace BciNoMovementDataSchema.TaskLogic
{
    #pragma warning disable // Disable all warnings

    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class BciNoMovementTaskLogic
    {
    
        private double _valveOpenTime = 0.1D;
    
        private double _lowActivityTime = 1D;
    
        private double _lickResponseTime = 2D;
    
        private bool _waitForLick = true;
    
        private bool _enableSoundOnRewardZoneEntry = true;
    
        private double _noMovementTimeBeforeTrial = 0D;
    
        private double _interTrialInterval = 0.5D;
    
        private double _maxTrialDuration = 20D;
    
        private double _rewardConsumeTime = 2D;
    
        private double _closePosition = 19D;
    
        private double _farPositionOffset = 8D;
    
        private double _maxBciSpeed = 10D;
    
        /// <summary>
        /// Interval (s) the valve stays open for water delivery.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("valveOpenTime")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="valveOpenTime")]
        [System.ComponentModel.DescriptionAttribute("Interval (s) the valve stays open for water delivery.")]
        public double ValveOpenTime
        {
            get
            {
                return _valveOpenTime;
            }
            set
            {
                _valveOpenTime = value;
            }
        }
    
        /// <summary>
        /// Duration (s) BCI activity must stay low before starting anew trial.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("lowActivityTime")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="lowActivityTime")]
        [System.ComponentModel.DescriptionAttribute("Duration (s) BCI activity must stay low before starting anew trial.")]
        public double LowActivityTime
        {
            get
            {
                return _lowActivityTime;
            }
            set
            {
                _lowActivityTime = value;
            }
        }
    
        /// <summary>
        /// Interval (s) for the animal to collect reward. Only applies if waitForLick is true.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("lickResponseTime")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="lickResponseTime")]
        [System.ComponentModel.DescriptionAttribute("Interval (s) for the animal to collect reward. Only applies if waitForLick is tru" +
            "e.")]
        public double LickResponseTime
        {
            get
            {
                return _lickResponseTime;
            }
            set
            {
                _lickResponseTime = value;
            }
        }
    
        /// <summary>
        /// Determines whether the animal must lick to trigger reward delivery. If false, reward is immediately delivered.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("waitForLick")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="waitForLick")]
        [System.ComponentModel.DescriptionAttribute("Determines whether the animal must lick to trigger reward delivery. If false, rew" +
            "ard is immediately delivered.")]
        public bool WaitForLick
        {
            get
            {
                return _waitForLick;
            }
            set
            {
                _waitForLick = value;
            }
        }
    
        /// <summary>
        /// Enables audio feedback on reward zone entry.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("enableSoundOnRewardZoneEntry")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="enableSoundOnRewardZoneEntry")]
        [System.ComponentModel.DescriptionAttribute("Enables audio feedback on reward zone entry.")]
        public bool EnableSoundOnRewardZoneEntry
        {
            get
            {
                return _enableSoundOnRewardZoneEntry;
            }
            set
            {
                _enableSoundOnRewardZoneEntry = value;
            }
        }
    
        /// <summary>
        /// Interval (s) subjects must not move for to start a new trial.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("noMovementTimeBeforeTrial")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="noMovementTimeBeforeTrial")]
        [System.ComponentModel.DescriptionAttribute("Interval (s) subjects must not move for to start a new trial.")]
        public double NoMovementTimeBeforeTrial
        {
            get
            {
                return _noMovementTimeBeforeTrial;
            }
            set
            {
                _noMovementTimeBeforeTrial = value;
            }
        }
    
        /// <summary>
        /// Interval (s) between trials.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("interTrialInterval")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="interTrialInterval")]
        [System.ComponentModel.DescriptionAttribute("Interval (s) between trials.")]
        public double InterTrialInterval
        {
            get
            {
                return _interTrialInterval;
            }
            set
            {
                _interTrialInterval = value;
            }
        }
    
        /// <summary>
        /// Maximum trial duration (s)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("maxTrialDuration")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="maxTrialDuration")]
        [System.ComponentModel.DescriptionAttribute("Maximum trial duration (s)")]
        public double MaxTrialDuration
        {
            get
            {
                return _maxTrialDuration;
            }
            set
            {
                _maxTrialDuration = value;
            }
        }
    
        /// <summary>
        /// Interval (s) to wait for the animal to consume a delivered reward.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rewardConsumeTime")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewardConsumeTime")]
        [System.ComponentModel.DescriptionAttribute("Interval (s) to wait for the animal to consume a delivered reward.")]
        public double RewardConsumeTime
        {
            get
            {
                return _rewardConsumeTime;
            }
            set
            {
                _rewardConsumeTime = value;
            }
        }
    
        /// <summary>
        /// Position (mm) of the manipulator when the spout is the closest to the animal.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("closePosition")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="closePosition")]
        [System.ComponentModel.DescriptionAttribute("Position (mm) of the manipulator when the spout is the closest to the animal.")]
        public double ClosePosition
        {
            get
            {
                return _closePosition;
            }
            set
            {
                _closePosition = value;
            }
        }
    
        /// <summary>
        /// Offset applied to closePosition to determine the furthest position the spout can travel to.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("farPositionOffset")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="farPositionOffset")]
        [System.ComponentModel.DescriptionAttribute("Offset applied to closePosition to determine the furthest position the spout can " +
            "travel to.")]
        public double FarPositionOffset
        {
            get
            {
                return _farPositionOffset;
            }
            set
            {
                _farPositionOffset = value;
            }
        }
    
        /// <summary>
        /// Maximum speed of the manipulator in mm/s when controlled by the BCI.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("maxBciSpeed")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="maxBciSpeed")]
        [System.ComponentModel.DescriptionAttribute("Maximum speed of the manipulator in mm/s when controlled by the BCI.")]
        public double MaxBciSpeed
        {
            get
            {
                return _maxBciSpeed;
            }
            set
            {
                _maxBciSpeed = value;
            }
        }
    
        public System.IObservable<BciNoMovementTaskLogic> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(
                new BciNoMovementTaskLogic
                {
                    ValveOpenTime = _valveOpenTime,
                    LowActivityTime = _lowActivityTime,
                    LickResponseTime = _lickResponseTime,
                    WaitForLick = _waitForLick,
                    EnableSoundOnRewardZoneEntry = _enableSoundOnRewardZoneEntry,
                    NoMovementTimeBeforeTrial = _noMovementTimeBeforeTrial,
                    InterTrialInterval = _interTrialInterval,
                    MaxTrialDuration = _maxTrialDuration,
                    RewardConsumeTime = _rewardConsumeTime,
                    ClosePosition = _closePosition,
                    FarPositionOffset = _farPositionOffset,
                    MaxBciSpeed = _maxBciSpeed
                }));
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    public partial class SerializeToJson
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value));
        }

        public System.IObservable<string> Process(System.IObservable<BciNoMovementTaskLogic> source)
        {
            return Process<BciNoMovementTaskLogic>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BciNoMovementTaskLogic>))]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<BciNoMovementTaskLogic>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder().Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<BciNoMovementTaskLogic> source)
        {
            return Process<BciNoMovementTaskLogic>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<BciNoMovementTaskLogic>))]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<BciNoMovementTaskLogic>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder().Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}